# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc243749db10f5001030701d49c570354ff3f5f3e893f95d2e82a82dfefc4e3458c225636849feab7545b3080f6bd13e0d540aba7c0656d113bde817b026e946

test:
  secret_key_base: 435a87b91a01203479b1942bb233a5ba7059f636018fc5dcc2c56257cc964e80e7e22158a9a2f781dc4715c8e164a7f8c12473de7381c7a51c9ac023b7d56fdb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
